name: Android Build & Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v0
      with:
        sdk-platform: '35'
        sdk-build-tools: '35.0.0'
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build Debug APK
      run: ./gradlew :ecomm:assembleDebug
      
    - name: Build Release APK
      run: ./gradlew :ecomm:assembleRelease
      
    - name: Run Unit Tests
      run: ./gradlew :ecomm:testDebugUnitTest
      
    - name: Run Lint Check
      run: ./gradlew :ecomm:lintDebug
      
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: ecomm-debug-apk
        path: ecomm/build/outputs/apk/debug/ecomm-debug.apk
        
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: ecomm-release-apk
        path: ecomm/build/outputs/apk/release/ecomm-release.apk
